site_name: Delta Lake Documentation
site_url: https://github.com/delta-io/delta-rs
repo_url: https://github.com/delta-io/delta-rs
repo_name: delta-io/delta-rs

theme:
  name: material
  locale: en
  navigation_depth: 3
  features:
    - navigation.tracking
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.footer
    - content.tabs.link
nav:
  - Home: index.md
  - Installation: installation.md
  - Usage:
    - Overview: usage/index.md
    - Loading a Delta Table: usage/loading-table.md
    - Examining a Delta Table: usage/examining-table.md
    - Querying a Delta Table: usage/querying-delta-tables.md
    - Managing a Delta Table: usage/managing-tables.md
    - Writing Delta Tables: usage/writing-delta-tables.md
  - API Reference:
    - api/delta_table.md
    - api/schema.md
    - api/storage.md
not_in_nav: |
  /_build/

exclude_docs: |
  /_build/
  /mlc_config.json
  /src
  /requirements.txt
  *.py

plugins:
  - autorefs
  - mkdocstrings:
      handlers:
        python:
          path: [../python]
          options:
            show_root_toc_entry: false
            docstring_section_style: table
            filters: ["!^_", "^__init__$"]
            heading_level: 3
            show_source: false
            show_symbol_type_in_heading: true
            show_signature_annotations: true
            show_root_heading: false
            show_root_full_path: true
            separate_signature: true
            docstring_options:
              ignore_init_summary: false
            merge_init_into_class: true
          import:
            # for cross references
            - https://arrow.apache.org/docs/objects.inv
            - https://pandas.pydata.org/docs/objects.inv
  - search:
      lang: en
  - markdown-exec
  - macros:
      module_name: docs/_build/macro
  - mkdocs-simple-hooks:
      hooks:
        on_page_markdown: 'docs._build.hooks:on_page_markdown'

markdown_extensions:
  - admonition
  - pymdownx.details
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.snippets:
      base_path: ['.','docs/src/']
      check_paths: true
      dedent_subsections: true
  - footnotes

extra:
  python_api_url: https://delta-io.github.io/delta-rs/python/api_reference.html