[package]
name = "deltalake"
version = "0.17.0"
rust-version = "1.64"
authors = ["Qingping Hou <dave2008713@gmail.com>"]
homepage = "https://github.com/delta-io/delta.rs"
license = "Apache-2.0"
keywords = ["deltalake", "delta", "datalake"]
description = "Native Delta Lake implementation in Rust"
documentation = "https://docs.rs/deltalake"
repository = "https://github.com/delta-io/delta.rs"
readme = "../README.md"
edition = "2021"

[dependencies]
deltalake-core = { path = "../deltalake-core" }
deltalake-aws = { path = "../deltalake-aws", default-features = false, optional = true }
deltalake-azure = { path = "../deltalake-azure", optional = true }
deltalake-catalog-glue = { path = "../deltalake-catalog-glue", optional = true }

[features]
# All of these features are just reflected into the core crate until that
# functionality is broken apart
azure = ["deltalake-azure"]
arrow = ["deltalake-core/arrow"]
default = ["arrow"]
datafusion = ["deltalake-core/datafusion"]
datafusion-ext = ["datafusion"]
gcs = ["deltalake-core/gcs"]
glue = ["deltalake-catalog-glue"]
hdfs = []
json = ["deltalake-core/json"]
python = ["deltalake-core/python"]
s3-native-tls = ["deltalake-aws/native-tls"]
s3 = ["deltalake-aws/rustls"]
unity-experimental = ["deltalake-core/unity-experimental"]

[dev-dependencies]
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
chrono = { workspace = true, default-features = false, features = ["clock"] }
tracing = { workspace = true }

[[example]]
name = "basic_operations"
required-features = ["datafusion"]

[[example]]
name = "load_table"
required-features = ["datafusion"]

[[example]]
name = "recordbatch-writer"
required-features = ["arrow"]
