[package]
name = "deltalake"
version = "0.17.0"
rust-version = "1.64"
authors = ["Qingping Hou <dave2008713@gmail.com>"]
homepage = "https://github.com/delta-io/delta.rs"
license = "Apache-2.0"
keywords = ["deltalake", "delta", "datalake"]
description = "Native Delta Lake implementation in Rust"
documentation = "https://docs.rs/deltalake"
repository = "https://github.com/delta-io/delta.rs"
readme = "../README.md"
edition = "2021"

[dependencies]
deltalake-core = { path = "../deltalake-core" }
deltalake-catalog-glue = { path = "../deltalake-catalog-glue", optional = true }

[features]
# All of these features are just reflected into the core crate until that
# functionality is broken apart
azure = ["deltalake-core/azure"]
arrow = ["deltalake-core/arrow"]
default = ["arrow", "deltalake-core/parquet"]
datafusion = ["deltalake-core/datafusion"]
datafusion-ext = ["datafusion"]
gcs = ["deltalake-core/gcs"]
glue = ["deltalake-catalog-glue"]
glue-native-tls = ["deltalake-catalog-glue/native-tls"]
hdfs = ["deltalake-core/hdfs"]
# used only for integration testing
integration_test = ["deltalake-core/integration_test"]
json = ["deltalake-core/json"]
python = ["deltalake-core/python"]
s3-native-tls = ["deltalake-core/s3-native-tls"]
s3 = ["deltalake-core/s3"]
unity-experimental = ["deltalake-core/unity-experimental"]

[dev-dependencies]
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
chrono = { workspace = true, default-features = false, features = ["clock"] }
log = "*"

[[example]]
name = "basic_operations"
required-features = ["datafusion"]

[[example]]
name = "load_table"
required-features = ["datafusion"]

[[example]]
name = "recordbatch-writer"
required-features = ["arrow"]
