version: "3.9"

# Run below on the host to create the network first:
# docker network create delta-checkpoint

networks:
  default:
    external:
      name: delta-checkpoint

services:
  localstack:
    image: localstack/localstack
    ports:
      - "4566:4566"
      - "${PORT_WEB_UI-8080}:${PORT_WEB_UI-8080}"
    environment:
      - SERVICES=s3,iam,lambda
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - PORT_WEB_UI=8080
      - LAMBDA_EXECUTOR=docker
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOST_TMP_FOLDER=${TMPDIR}
      - LAMBDA_DOCKER_NETWORK=delta-checkpoint
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:4566/health" ]
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"

  setup:
    image: localstack/localstack
    depends_on:
      - localstack
    entrypoint: "/bin/bash"
    command:
      - /setup-localstack.sh
    volumes:
      - "./bin/setup-localstack.sh:/setup-localstack.sh"
      - "./lambda-delta-checkpoint.zip:/lambda-delta-checkpoint.zip"

