rust:
  - delta-inspect/**/*
  - proofs/**/*
  - rust/**/*

binding/python:
  - python/**/*

ci:
  - .github/**.*

documentation:
  - README.adoc
  - ./**/README.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - python/docs/**/*

storage/aws:
  - aws/**/*

delta-inspect:
  - delta-inspect/**/*

binding/rust:
  - rust/**/*

proofs:
  - proofs/**/*

tlaplus:
  - tlaplus/**/*
